### ISSUE TITLE
RegistryOptions.GetScopeByExtension causes NullReferenceException

### ISSUE THREAD

**Issue by Key-os** [danipen/TextMateSharp#33]
if language doesn't have extensions, NullReferenceException is thrown. 
Solution: add 
```
if (language.Extensions == null)
    continue;
```
before foreach loop, as by RegistryOptions.GetLanguageByExtension

**Comment by danipen** [comment]
The null check is already there:
https://github.com/danipen/TextMateSharp/blob/7845809e3e69162a3a6a1ee001d953f1dead3745/src/TextMateSharp.Grammars/RegistryOptions.cs#L55

**Comment by Key-os** [comment]
Yes, It is in GetLanguageByExtension, but not in GetScopeByExtension
https://github.com/danipen/TextMateSharp/blob/7845809e3e69162a3a6a1ee001d953f1dead3745/src/TextMateSharp.Grammars/RegistryOptions.cs#L77

**Comment by danipen** [comment]
Fixed in https://github.com/danipen/TextMateSharp/commit/1a816bb5ed9864aa88c252848dabafeea6b5a9ae

**Comment by danipen** [comment]
A new package [TextMateSharp 1.0.44](https://www.nuget.org/packages/TextMateSharp/1.0.44) was recently published on NuGet Gallery with this fix.
