### ISSUE TITLE
Support for arm32 and arm64

### ISSUE THREAD

**Issue by alexandrehtrb** [danipen/TextMateSharp#40]
Hello,

First, thanks for this project!

I am using TextMateSharp through AvaloniaEdit.TextMate project and I would like to have support for arm and arm64.

I do not have an arm machine to test it, but the `onigwrap.dll` seem to be missing when I compile for `win-arm64`, although it appears for `win-x64`.

I would like support for the following .NET target runtimes:

linux-arm64
osx-x64
osx-arm64
win-arm
win-arm64

Does it work on arm machines?

**Comment by danipen** [comment]
Hi. ARM is only supported in macos at this moment. Supporting arm on win/Linux should be straightforward just [compiling onigwrap](https://github.com/danipen/TextMateSharp/tree/master/onigwrap)  for those archs. A PR for that would be welcome.

**Comment by EdWordy** [comment]
Does this mean that android isn't supported? I have an Avalonia app that I'm building for android and TextMate doesn't seem to run without throwing any specific errors and I'm guessing it isn't supported but I was unsure.

**Comment by EdWordy** [comment]
I see, what file type that would that be then for android? I'm not sure where to get started for compiling for android to be honest haha.

**Comment by danipen** [comment]
There are some instructions here: https://github.com/danipen/TextMateSharp/tree/master/onigwrap

**Comment by EdWordy** [comment]
I built a file using the docker image here: https://github.com/sjitech/android-gcc-toolchain

I think I've been able to package it into a nuGet package using the textmatesharp source, but I'm unsure of how to link it against the existing code and subsequently the avalonia android builds I've been trying all night have failed.

**Comment by alexandrehtrb** [comment]
I think that the oniguruma .dlls / .so could be compiled using a GitHub Actions workflow, for each target runtime, including arm.

GitHub Actions machines are x64, but I believe that they can compile for ARM without problem.

(I don't have an ARM machine to test whether it would work flawlessly)

**Comment by EdWordy** [comment]
I've tried rebuilding with arm-none-eabi-gcc to no avail. I don't know if I'm building textmatesharp properly with the new native libraries after but I'm unable to get android to find the files afterwards and instead get a:

`[monodroid assembly]: Shared library 'onigwrap' not loaded, p/invoke 'onigwrap_create' may fail`

**Comment by danipen** [comment]
> I think that the oniguruma .dlls / .so could be compiled using a GitHub Actions workflow, for each target runtime, including arm.

Absolutely! Building oniguruma/onigwrap DLLs are a nightmare right now. A PR for that would be more than welcome!

**Comment by aikawayataro** [comment]
I set up a CI to build onigwrap with static oniguruma for different platforms. You can see it here:
https://github.com/aikawayataro/onigwrap-build
https://github.com/aikawayataro/onigwrap-build/actions/runs/10253696438

Do you want to integrate this? I would like to see at least Linux arm64 support :grin:

**Comment by danipen** [comment]
Yes this project has a CI build for the managed part but the unmanaged part is unfortunately [manual yet](https://github.com/danipen/TextMateSharp/blob/master/onigwrap/README.md). A PR to automatize it would be more than welcome.

**Comment by aikawayataro** [comment]
I see. The problem is that I'm not very familiar how to ship dotnet with native assets, so that's why I did this in a separate repo, not as a pull request :grin:
Can you give me some points?

**Comment by danipen** [comment]
Oh ok! Unfortunately I don't have experience mixing managed and unmanaged build. I'd love to hear someone here that already knows the best practives of doing it.

That being said ... I'd say that as the managed part is already solved, I guess this is just a matter of setting up a workflow to automatize building the unmanaged libraries (first oniguruma and then onigwrap... that includes oniguruma). The source of thruth now is following the [build instructions](https://github.com/danipen/TextMateSharp/blob/master/onigwrap/README.md). Once onigwrap is built, we just need to copy the generated native binaries into [this folder](https://github.com/danipen/TextMateSharp/tree/master/src/TextMateSharp/Internal/Oniguruma/Native). Once the native binaries have been updated I guess the CI should commit then to have an updated version of them and then we could trigger the already [existing managed build](https://github.com/danipen/TextMateSharp/blob/master/.github/workflows/dotnet.yml). 

So any help with this would be more than than welcome 🤗!

**Comment by aikawayataro** [comment]
Hm, I think I could do that, something like when onigwrap.[ch] or workflow file is edited or workflow is triggered manually, build everything and create a pull request with freshly built binaries.
I'm sure there's a way to make it more idiomatic, but I just don't know how.

**Comment by danipen** [comment]
That sounds good because a new PR with the new native assets will run unit tests in the three platforms.

A couple of things to take into account:

- note that macOS binaries need to be built in both 32 and 64 (universal binaries). Instructions are provided in the build instructions.
- Linux arm64 is not supported yet in the csproj but once the native assets are there we can probably add support for it later.

**Comment by aikawayataro** [comment]
> note that macOS binaries need to be built in both 32 and 64 (universal binaries). Instructions are provided in the build instructions.

Instruction only mentions x86_64 and arm64 :thinking:. I build it like this: https://github.com/aikawayataro/onigwrap-build/actions/runs/10253696438/job/28366917052

> Linux arm64 is not supported yet in the csproj but once the native assets are there we can probably add support for it later.

Hmm, have you seen linked action? There are builds for Linux aarch64.

**Comment by danipen** [comment]
Yes. For MacOS lipo tool does the trick. It's fine: https://github.com/aikawayataro/onigwrap-build/blob/c88b7a6356936f1ea72ba2dc1883f088b4742245/build.osx.sh#L22

> Hmm, have you seen linked action? There are builds for Linux aarch64.
Yes, I mean Linux x64 is not supported yet from TextMateSharp... (as you can see there are two different natives for windows but not for Linux [here](https://github.com/danipen/TextMateSharp/tree/master/src/TextMateSharp/Internal/Oniguruma/Native))

**Comment by aikawayataro** [comment]
Can you explain how the wasm build is supposed to work? I thought I should just compile onigwrap to .wasm, but instead you ship compiled oniguruma with onigwrap sources? Should it just ship .wasm file? Not sure how wasm works with dotnet.

**Comment by danipen** [comment]
For wasm, there are some things to take into account: 
- `libonig.a` needs to be compiled and copied [here](https://github.com/danipen/TextMateSharp/tree/master/src/TextMateSharp.Wasm). Instructions about how to compile for wasm, [here](https://github.com/danipen/TextMateSharp/tree/master/onigwrap#web-assembly).
- `libonig.a`, `oniguruma.h`, `onigwrap.c` and `onigwrap.h` are [packed into the nugets](https://github.com/danipen/TextMateSharp/blob/46c63c57d3057ba18e4488836a1709136ea3f47e/src/TextMateSharp.Wasm/TextMateSharp.Wasm.csproj#L19). So I guess that when compiling the latest oniguruma sources, we need to fetch the latest `oniguruma.h` from the source repository and replace the [local copy](https://github.com/danipen/TextMateSharp/tree/master/onigwrap/src) on this repository.
- `libonig.a` and `onigwrap.c` are [packaged](https://github.com/danipen/TextMateSharp/blob/46c63c57d3057ba18e4488836a1709136ea3f47e/src/TextMateSharp.Wasm/TextMateSharp.Wasm.props#L8) as `<NativeFileReference>`s.

This is the original PR, for more context: https://github.com/danipen/TextMateSharp/pull/36

**Comment by aikawayataro** [comment]
Yes, I can see *how* to do it, Im asking why it done like that. Why can't you just ship compiled wasm library?

https://github.com/dotnet/AspNetCore.Docs/blob/main/aspnetcore/blazor/webassembly-native-dependencies.md
says:

> Generally, any portable native code can be used as a native dependency with Blazor WebAssembly. You can add native dependencies to C/C++ code or code previously compiled using Emscripten:
> 
>Object files (.o)
>Archive files (.a)
>Bitcode (.bc)
>Standalone WebAssembly modules (.wasm)

Why do you not ship a compiled wasm? Are there any end user issues with this?

**Comment by Numpsy** [comment]
I've tried in an Avalonia app at various points, with varying degrees of success (I need to get back to giving it a proper test with the Avalonia 11.1 release build actually)

> Why do you not ship a compiled wasm? Are there any end user issues with this?

One possible issue is with this comment in that Microsoft page linked above:
```
Prebuilt dependencies typically must be built using the same version of Emscripten used to build the .NET WebAssembly runtime.
```

So you might end up needing different builds for different versions of .NET (i think SkiaSharp has to ship multiple different builds because of that)

**Comment by aikawayataro** [comment]
It seems emsdk version depends on dotnet version,
From SkiaSharp:
```
    <NativeFileReference Include="$(SkiaSharpStaticLibraryPath)\2.0.23\*.a" Condition="$([MSBuild]::VersionEquals($(TargetFrameworkVersion), '6.0'))" />
    <NativeFileReference Include="$(SkiaSharpStaticLibraryPath)\3.1.12\st\*.a" Condition="$([MSBuild]::VersionEquals($(TargetFrameworkVersion), '7.0'))" />
    <NativeFileReference Include="$(SkiaSharpStaticLibraryPath)\3.1.34\st\*.a" Condition="$([MSBuild]::VersionEquals($(TargetFrameworkVersion), '8.0'))" />
```

It will be necessary to refactor the project to make different targets work.
I still don't think committing compiled blobs to the repository is the right way to handle natives, and after looking at how others do it, the right way is when CI  builds `$(pkg).Native.$(target)` package as an artifact (and publishes it to nuget if there is a release tag) right after it builds everything.
Maybe I should create a separate package `Onigwrap`? Then migration to it should be relatively easy.

**Comment by danipen** [comment]
So are you suggesting creating a new repo and nuget package for onigwrap?

**Comment by danipen** [comment]
A separate package would be good but I'd like to manage the sources in this repo (not in a external repo) as all belongs to the same project IMO.

**Comment by aikawayataro** [comment]
I can start my work on the package and when the work is done, you can adopt to your project, do you like the idea?

**Comment by danipen** [comment]
Sounds good.

**Comment by Numpsy** [comment]
> By the way, can you share a minimal wasm project for me to play with?

I only have work projects ATM, will try to create a minimal test app.

**Comment by Numpsy** [comment]
Maybe this is going off on too much of a tangent, but - a thought/question about builds whilst I think of it:

There is a thread at https://github.com/AvaloniaUI/Avalonia/issues/9503 about the possibility of statically linking SkiaSharp/HarfbuzzSharp into NativeAOT Avalonia apps.

I wonder whether it would be feasible to statically link onigwrap using that technique? (I've never tried to do it, so I don't know how much work it might be to try it out)

**Comment by aikawayataro** [comment]
> I only have work projects ATM, will try to create a minimal test app.

I really appreciate that!

> I wonder whether it would be feasible to statically link onigwrap using that technique? (I've never tried to do it, so I don't know how much work it might be to try it out)

I see that's reasonable, it will require to ship two types of library for each supported target, but I'm sure it can be done. Will have a look at it after I get the base package working.

**Comment by aikawayataro** [comment]
You can see my work here: https://github.com/aikawayataro/Onigwrap
It took me a while to understand how to properly package native runtimes and Wasm. SkiaSharp helped me a lot as a reference :grin:.

The Wasm thing works well, both as an included project and as a nuget package, no extra action required, it just works. There's a sample project in the solution that you can test (download the `runtimes` artifact from actions and unpack it to runtimes directory in the project root).

I've added a lot of runtimes, but if something is missing, I can easily add it. Full list here:
```
runtimes/
├── linux-arm64
│   └── native
│       └── libonigwrap.so
├── linux-musl-arm64
│   └── native
│       └── libonigwrap.so
├── linux-musl-x64
│   └── native
│       └── libonigwrap.so
├── linux-x64
│   └── native
│       └── libonigwrap.so
├── osx
│   └── native
│       └── libonigwrap.dylib
├── wasm
│   ├── 2.0.23
│   │   └── libonigwrap.a
│   ├── 3.1.12
│   │   └── libonigwrap.a
│   └── 3.1.34
│       └── libonigwrap.a
├── win-arm64
│   └── native
│       └── libonigwrap.dll
├── win-x64
│   └── native
│       └── libonigwrap.dll
└── win-x86
    └── native
        └── libonigwrap.dll
```

There are 3 Wasm libraries for each dotnet (6.0, 7.0, 8.0).

I still think it's easier to maintain this project as an external package, but if you still want it, I want to hear from you.

**Comment by danipen** [comment]
Yes I think you're right. It sounds like it's easier to maintain as external package.

**Comment by aikawayataro** [comment]
What is the next step? Should I publish it to the NuGet gallery? I can also add you as a collaborator so you can set things up the way you want :grin:

**Comment by danipen** [comment]
Sounds good yes. Yes next steps are:

- publishing the nuget package in the nuget gallery.
- creating a pr in this repo to replace onigwrap with the nuget package and remove from here the unneeded resources.

**Comment by aikawayataro** [comment]
I'll handle the nuget package and have sent you a collaborator invitation
