### ISSUE TITLE
Feature request - add rule name to ParsedThemeRule and language-configuration classes

### ISSUE THREAD

**Issue by dmitry-medvedev** [danipen/TextMateSharp#48]
Hi,

We use TextMateSharp in our new generic parser.

There are a few features that we'd like to see in the next version of TextMateSharp

Please consider adding the name of the matched token to the ParsedThemeRule, so it's possible to match the token name from the tokens (right now, we can only get colors from the token). Here's a code snippet

                foreach (var themeRule in theme.Match(token.Scopes))
                {
                    name = themeRule.name;
                }

We use the name of the matched token for our lexical styles collection.

Please also consider parsing language-configuration.json into C# classes. We use language configuration to get code snippets, code folding, indentation rules, etc.

Another small issue - IStateStack does not uniquely identifies the stack object; please add RuleId (at least) to this interface.
BTW, StateStack.GetHashCode throws exceptions most of the time.

Finally, please consider signing TextMateSharp assemblies with strong names, as we're getting errors when adding the package to our strong-name signed assemblies.

We were able to work around most of these issues (except for the last one), by porting/changing some code from TextMateSharp.
Happy to send you our modifications if needed. 

I'm attaching a screenshot for your reference.
![image](https://user-images.githubusercontent.com/64202511/234492419-1b6f492c-da97-4b46-afda-96b9af93aeea.png)

Kind regards,
Dmitry
dmitry.medvedev@alternetsoft.com

**Comment by danipen** [comment]
@dmitry-medvedev sure! PRs are more than welcome.

**Comment by danipen** [comment]
If you submit changes please separate them into different PRs for simplicity. Thanks!

**Comment by danipen** [comment]
About the last one a PR is coming: https://github.com/danipen/TextMateSharp/pull/49

**Comment by danipen** [comment]
A new version of `TextMateSharp` with strong names has been published. Check it out here https://www.nuget.org/packages/TextMateSharp/1.0.53

**Comment by dmitry-medvedev** [comment]
Many thanks for your reply, here are our modifications related to getting the token name from matched rules (based n 1.0.51 codebase)

[ThemeWithNames.zip](https://github.com/danipen/TextMateSharp/files/11339013/ThemeWithNames.zip)

**Comment by dmitry-medvedev** [comment]
I've attached helper classes for loading language configuration.

[LanguageConfiguration.zip](https://github.com/danipen/TextMateSharp/files/11339328/LanguageConfiguration.zip)

**Comment by danipen** [comment]
Would be possible to create pull request for those? Thanks!

**Comment by dmitry-medvedev** [comment]
Will do that, but we will need to re-implement json serialization of the Language configuration using System.Json (as it was changed in 1.0.52)

**Comment by danipen** [comment]
Fixed by #50.
