### ISSUE TITLE
Release a nuget package with the latest code changes?

### ISSUE THREAD

**Issue by Numpsy** [danipen/TextMateSharp#56]
Hi,

Would it be possible to get a new version released that contains https://github.com/danipen/TextMateSharp/pull/53 ?

Reason for asking: I just tried to build an application of mine that uses AvaloniaEdit / TextMateSharp as .NET 8 using the RC1 release, and it fell over at runtime due to the reflection based serializers being disabled by default - and I think that change should fix it by using the serializer context in more places.

Thanks,

**Comment by danipen** [comment]
Done! 😃

https://www.nuget.org/packages/TextMateSharp/1.0.56

**Comment by Numpsy** [comment]
Thanks, all working ok now :-)
