### ISSUE TITLE
Use [Flags] enum for FontStyle

### ISSUE THREAD

**Issue by Khitiara** [danipen/TextMateSharp#58]
TextMateSharp.Themes.FontStyle is currently a class with int fields representing a bitfield. This sort of bitfield is normally represented in c#/dotnet as an enum with the `[Flags]` attribute, so FontStyle should be updated to match.

**Comment by danipen** [comment]
Agree. The implementation is a port from tm4e so it matches that implementation. But there are some areas for improvement.

@Khitiara would you like to add a PR for this?

**Comment by Khitiara** [comment]
ill fork it and do it, this should be a relatively quick thing

**Comment by danipen** [comment]
Merged! Thanks for the contribution.
