### ISSUE TITLE
Unexpected behavior in indexes and length.

### ISSUE THREAD

**Issue by thempen** [danipen/TextMateSharp#63]
Hello,

I am confused about the StartIndex, EndIndex and Length of IToken.
I was programming a demo file to parse proto (ProtoBuf) messages. 
While parsing a comment line, the string had 26 chars. 
The EndIndex and Length value were both resulting in 27 chars.

This is the snippet of the textmate json:
```
    "comments": {
      "patterns": [
        {
          "name": "comment.block.proto",
          "begin": "/\\*",
          "end": "\\*/"
        },
        {
          "name": "comment.line.double-slash.proto",
          "begin": "//",
          "end": "$\\n?"
        }
      ]
    }
```

For me, this looks like a bug, however in the example of the readme, there is also code, fixing the length values.
```
int startIndex = (token.StartIndex > line.Length) ? line.Length : token.StartIndex;
int endIndex = (token.EndIndex > line.Length) ? line.Length : token.EndIndex;
```

Is this a nasty fix, or is it intended behavior? Why do I need this behavior?
I would like to use the length values to detect possible parsing errors, but without knowing the behavior, this is not possible.

**Comment by danipen** [comment]
Probably the API is a bit confusing, and just to clarify, please note that in a "real world" application, the length and the end index [are not used](https://github.com/AvaloniaUI/AvaloniaEdit/blob/f92e5527c0f6ef1a1a6f6d2dc904af5688315949/src/AvaloniaEdit.TextMate/TextMateColoringTransformer.cs#L154). In that example to calculate the `endIndex`, it's taking into account the next token's `startIndex` or the line length if the next token is `null`.

So, right now it's working like this, imagine the following line:
```csharp
// comment
```

These are the indexes:
```
0 1 2 3 4 5 6 7 8 9
/ /   c o m m e n t
```

Right now, TextMate is returning the following tokens:
```
tokens[0]: startIndex=0; endIndex=2; length=2;
tokens[1]: startIndex=2; endIndex=10; length=8;
```

The `startIndex` is inclusive, and the `endIndex` is not inclusive, so it works like an interval `[startIndex, endIndex)`. The length is a [calculated property](https://github.com/danipen/TextMateSharp/blob/69616c19b39f458658c81570ab8cae6d61777e84/src/TextMateSharp/Internal/Grammars/Token.cs#L14).

You can see here the [implementation details](https://github.com/danipen/TextMateSharp/blob/69616c19b39f458658c81570ab8cae6d61777e84/src/TextMateSharp/Internal/Grammars/LineTokens.cs#L122).

I agree that probably the API would be more intuitive using the following values:
```
tokens[0]: startIndex=0; endIndex=1; length=2;
tokens[1]: startIndex=2; endIndex=9; length=8;
```

This implementation is a port of [tm4e](https://github.com/eclipse/tm4e), so just copied the same behavior in that repo and I didn't want to change the behavior to match the implementation in the upstream repository.

**Comment by thempen** [comment]
Thank you very much for the quick response! Now it is clear to me.
